# Generated by Django 5.2.6 on 2025-09-27 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='podcast',
            new_name='episode',
        ),
        migrations.RenameField(
            model_name='vocabulary',
            old_name='podcast',
            new_name='episode',
        ),
    ]
