# Generated by Django 5.2.6 on 2025-09-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_podcast_script_episode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='time_end',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='script',
            name='time_start',
            field=models.DurationField(),
        ),
    ]
